# 回调地狱&Promise

> 在 JS 中，我们经常通过回调来实现异步逻辑，一旦嵌套层级多了，代码结构就容易变得很不直观，这种多层的回调嵌套回调的结构，就叫做“回调地狱”。
>
> 解决方法：使用ES6中的Promise来解决，但是Promise只是单纯的解决回调地狱的问题，不能减少代码量，反而会多几行代码

## 回调地狱

多层的回调嵌套结构，就叫做“回调地狱”。

下面为一个“回调地狱”的例子：

```javascript
getFile(path.join(__dirname, '/1.txt'), function (data) {
    console.log('成功的结果: ' + data);

    getFile(path.join(__dirname, '/2.txt'), function (data) {
      	console.log('成功的结果: ' + data);

      	getFile(path.join(__dirname, '/3.txt'), function (data) {
       		console.log('成功的结果: ' + data);
          
          	getFile(path.join(__dirname, '/4.txt'), function (data) {
                console.log('成功的结果: ' + data);
            })
    	})
  	})
})
```



## Promise

### 什么是Promise？

1. Promise 是一个 构造函数，可以通过 `new Promise()` 得到一个 Promise 的实例；

2. 在 Promise 上，有两个函数，分别叫做 `resolve（成功之后的回调函数）` 和 `reject（失败之后的回调函数）`

3. 在 Promise 构造函数的 Prototype 属性上，有一个 .then() 方法，也就说，只要是 Promise 构造函数创建的实例，都可以访问到 .then() 方法

4. Promise 表示一个 异步操作；每当我们 new 一个 Promise 的实例，
   这个实例，就表示一个具体的异步操作；

5. 既然 Promise 创建的实例，是一个异步操作，那么，这个异步操作的结果，只能有两种状态：

    - 状态1： 异步执行**成功**了，需要在内部调用成功的回调函数 resolve 把结果返回给调用者；

    - 状态2： 异步执行**失败**了，需要在内部调用失败的回调函数 reject 把结果返回给调用者；

    - 由于 Promise 的实例，是一个异步操作，所以，内部拿到操作的结果后，无法使用 return 把操作的结果返回给调用者； 这时候只能使用回调函数的形式，来把成功或失败的结果，返回给调用者；

6. 我们可以在 new 出来的 Promise 实例上，调用 `.then()` 方法，
  **【预先】 为 这个 Promise 异步操作，指定 成功（resolve） 和 失败（reject） 回调函数**；

###　Promise的具体使用

#### 创建promise实例

1.  形式上的Promise实例：
  > 注意：这里 new 出来的 promise， 只是代表 【形式上】的一个异步操作；
  >
  > 什么是形式上的异步操作：就是说，我们只知道它是一个异步操作，但是做什么具体的异步事情，目前还不清楚

```javascript
var promise = new Promise()
```

2. 具体的Promise实例

  > 具体的异步操作：使用 function 指定一个具体的异步操作
  >
  > 注意：promise实例一旦创建，就会立即执行Promise构造函数的参数function中的异步操作。

```javascript
var promise = new Promise(function(){
  // 这个 function 内部写的就是具体的异步操作
})
```
- 若不希望立即执行回调，需要将new Promise放到一个方法中，通过用方法来执行

```javascript
const fs = require('fs');
const path = require('path');

// 立即执行的promise
var promise = new Promise(function(){
  fs.readFile(path.join(__dirname,'./1.txt'),'utf-8',(err,data)=>{
    if (err){
      throw err;
    }
    console.log(data);
  })
})

// 通过调用函数执行的promise
function getFile(fpath){
  var promise = new Promise(function(){
    fs.readFile(fpath,'utf-8',(err,data)=>{
      if (err){
        throw err;
      }
      console.log(data);
    })
  }) 
}
getFile(path.join(__dirname,'./1.txt'));

```

#### 通过.then()预定义成功/失败的回调

```javascript
const fs = require('fs');
const path = require('path');

function getFile(filepath){
  var promise = new Promise(function (resolve, reject) {
    fs.readFile(filepath, 'utf-8', function (err, data) {
      if (err) {
        reject(err);
      }
      resolve(data);
    })
  })
  // 通过return一个promise实例，可以在传递filepath的同时指定成功/失败的回调
  return promise;
}

getFile(filepath).then(function(data){
  console.log('成功啦！！ : ' + data);
},function(err){
  console.log(err.message);
})

```

### 使用promise解决回调地狱

#### 解决回调地狱

> 再每一次的`.then()`的回调中，返回一个新的promise实例，然后继续`.then` 添加回调。

```javascript

getFile(path.join(__dirname, './1.txt'))
  .then(function (data) {
    console.log(data);
    // return 一个文件2的promise，从而文件二的.then()可以直接链式调用
    return getFile(path.join(__dirname, './2.txt'));
  })
  .then(function (data) {
    console.log(data);
    return getFile(path.join(__dirname, './3.txt'));
  })
  .then(function (data) {
    console.log(data);
  })

```

#### 捕获异常的两种方式

- 当前面的promise的`.then`执行失败了，可以继续执行后面的`.then`，而不是中断操作

  > 方法：单独为每一个promise 通过 .then 来指定一下失败的回调

- 如果后续的promise的操作依赖于前一个promise的执行结果，如果前面的失败了，则后面的也没有执行的意义，此时一旦出现错误，立即中止所有的promise的执行。

  > 方法：利用.catch 捕获异常
  >
  > **catch的作用**：如果前面的任何Promise执行失败，立即中止所有的promise的执行，并马上进入catch中去处理Promise抛出的异常。

```javascript
const fs = require('fs');
const path = require('path');

function getFile(fpath) {
  return new Promise(function (resolve, reject) {
    fs.readFile(fpath, 'utf-8', (err, data) => {
      if (err) {
        reject(err);
      }
      resolve(data);
    })
  })
}

// 1. 前面的失败了，也不要影响后面的操作
// 给每一个的promise添加失败的回调

getFile(path.join(__dirname, './11.txt'))
  .then(function (data) {
    console.log(data);
    return getFile(path.join(__dirname, './2.txt'));
  },function(err){
    console.log(err.message);
    return getFile(path.join(__dirname, './2.txt'));
  })
  .then(function (data) {
    console.log(data);
    return getFile(path.join(__dirname, './3.txt'));
  })
  .then(function (data) {
    console.log(data);
  })

// 2. 一旦失败，立即中止所有的promise
// 使用catch捕获异常

getFile(path.join(__dirname, './11.txt'))
  .then(function (data) {
    console.log(data);
    return getFile(path.join(__dirname, './2.txt'));
  })
  .then(function (data) {
    console.log(data);
    return getFile(path.join(__dirname, './3.txt'));
  })
  .then(function (data) {
    console.log(data);
  })
  .catch(function (err) {
    console.log('我是catch捕获的异常: ' + err.message);
  })
```
## jQuery中实现Promise

#### **$.Deferred**

jquery用`$.Deferred`实现了Promise规范，打印`$ .Deferred()` 可以得到一个类似`new Promise` 的对象，区别在于由于jquery的def对象本身就有resolve方法，所以我们不需要传入resolve参数。

这样也有一个弊端，即我们可以在外部调用resolve方法来改变def的状态。

因此：jquery提供了一个promise方法，就在def对象上，他可以返回一个受限的Deferred对象，所谓受限就是没有resolve、reject等方法，无法从外部来改变他的状态

```javascript
function runAsync(){
    var def = $.Deferred();
    //做一些异步操作
    setTimeout(function(){
        console.log('执行完成');
        def.resolve('随便什么数据');
    }, 2000);
    return def.promise(); //就在这里调用
}
```

#### **ajax与Deferred的关系**

jquery的ajax返回一个受限的Deferred对象，即没有resolve方法和reject方法的def对象，不能从外部改变状态。

支持.then() 链式调用

```javascript
  $('#btn').on('click', function () {
    $.ajax({
      url: './data.json',
      type: 'get',
      dataType: 'json'
    })
    .then(function (data) {
      console.log(data)
    })
  })
// 上面的代码等价于
  $('#btn').on('click', function () {
    $.ajax({
      url: './data.json',
      type: 'get',
      dataType: 'json',
      succcess: function(data){
          console.log(data);
      }
    })
  })

```

### 连续发送多个ajax请求

1. 异步发送多个ajax请求的时候也可能出现回调地狱，此时可以通过.then() 链式调用

```javascript
req1 = function(){
    return $.ajax(/*...*/);
}
req2 = function(){
    return $.ajax(/*...*/);
}
req3 = function(){
    return $.ajax(/*...*/);
}

req1().then(req2).then(req3).done(function(){
    console.log('请求发送完毕');
});
```

2. 也可以通过异步计数的方法解决

```javascript
//并行执行就只能用异步模式。并设置变量进行计数    
var num = 0;    
function isAllSuccess() {    
    num++;    
    if (num>=3)    
        console.log("三个ajax请求全部完成");    
}    
$.ajax({    
    url: "https://cnodejs.org/api/v1/topics?tab=good",    
    async: true,    
    success: function (data) {    
        console.log("ajax请求1 完成");    
        isAllSuccess();    
    }    
});    
$.ajax({    
    url: "https://cnodejs.org/api/v1/topics?tab=job",    
    async: true,    
    success: function (data) {    
        console.log("ajax请求3 完成");    
        isAllSuccess();    
    }    
});    
$.ajax({    
    url: "https://cnodejs.org/api/v1/topics?tab=share",    
    async: true,    
    success: function (data) {    
        console.log("ajax请求3 完成");    
        isAllSuccess();    
    }    
});  
```

